// This file is auto-generated by `pnpm gen:pages`.
// Do not edit by hand.

export type PageEntry = {
    folder: string
    path: string
};

export const pages: PageEntry[] = [
    { folder: "page-a", path: "pages/page-a" },
    { folder: "page-c", path: "pages/page-c" },
    { folder: "page-c-extracted", path: "pages/page-c-extracted" },
    { folder: "page-d", path: "pages/page-d" },
    { folder: "page-y-for-new", path: "pages/page-y-for-new" },
];
