// This file is auto-generated by `pnpm gen:pages`.
// Do not edit by hand.

export type PageEntry = {
    folder: string
    path: string
};

export const pages: PageEntry[] = [
    { folder: "page-a", path: "pages/page-a" },
    { folder: "page-b", path: "pages/page-b" },
    { folder: "page-c", path: "pages/page-c" },
    { folder: "page-d", path: "pages/page-d" },
];
