//@ts-check
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

function main() {
    const __filename = fileURLToPath(import.meta.url);
    const __dirname = path.dirname(__filename);

    const rootDir = path.resolve(__dirname, '..');
    const pagesDir = path.resolve(rootDir, 'pages');
    const outFile = path.resolve(rootDir, 'src', 'components', '9-pages.ts');

    try {
        const pages = listPageFolders(rootDir, pagesDir);
        const content = renderPagesTs(pages);

        fs.mkdirSync(path.dirname(outFile), { recursive: true });

        let prev = null;
        try {
            prev = fs.readFileSync(outFile, 'utf8');
        } catch {
            // ignore
        }

        if (prev === content) {
            console.log(`${toPosixPath(path.relative(rootDir, outFile))} is up to date (${pages.length} pages).`);
            process.exit(0);
        }

        fs.writeFileSync(outFile, content, 'utf8');
        console.log(`Wrote ${toPosixPath(path.relative(rootDir, outFile))} (${pages.length} pages).`);

        const urls = pages.map(
            (p) => `/${ensureTrailingSlash(pathForSiteUrl(p.path))}`,
        );
        console.log(`URLs:\n${urls.map((u) => `- ${u}`).join('\n')}`);
    } catch (err) {
        console.error(err instanceof Error ? err.message : String(err));
        process.exitCode = 1;
    }
}

function listPageFolders(rootDir, pagesDir) {
    if (!fs.existsSync(pagesDir)) {
        throw new Error(`Expected a "pages" folder at ${toPosixPath(path.relative(rootDir, pagesDir))}`);
    }

    const dirents = fs.readdirSync(pagesDir, { withFileTypes: true });
    const folders = dirents.filter((d) => d.isDirectory()).map((d) => d.name);

    const missingIndex = [];
    const pages = [];

    for (const folder of folders) {
        const folderAbs = path.resolve(pagesDir, folder);
        const indexAbs = path.resolve(folderAbs, 'index.html');

        if (!fs.existsSync(indexAbs)) {
            missingIndex.push(toPosixPath(path.relative(rootDir, indexAbs)));
            continue;
        }

        const rel = toPosixPath(path.relative(rootDir, folderAbs));
        pages.push({
            folder,
            path: `./${rel}`,
        });
    }

    if (missingIndex.length) {
        const message = [`Some subfolders in "pages/" are missing an index.html:`, ...missingIndex.map((p) => `- ${p}`),].join('\n');
        throw new Error(message);
    }

    pages.sort((a, b) => a.folder.localeCompare(b.folder));
    return pages;
}

function renderPagesTs(pages) {
    const lines = [];

    lines.push('// This file is auto-generated by `pnpm gen:pages`.');
    lines.push('// Do not edit by hand.');
    lines.push('');
    lines.push('export type PageEntry = {');
    lines.push('    folder: string');
    lines.push('    path: string');
    lines.push('};');
    lines.push('');
    
    lines.push('export const pages: PageEntry[] = [');
    for (const page of pages) {
        lines.push(`    { folder: ${JSON.stringify(page.folder)}, path: ${JSON.stringify(page.path)} },`);
    }
    lines.push('];');

    lines.push('');

    return lines.join('\n');
}

// Helper functions

function toPosixPath(path) {
    return path.replaceAll('\\', '/');
}

function ensureTrailingSlash(path) {
    return path.endsWith('/') ? path : `${path}/`;
}

/** Strip leading `./` for logging absolute-style paths. */
function pathForSiteUrl(storedPath) {
    return storedPath.startsWith('./') ? storedPath.slice(2) : storedPath;
}

main();
