import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const rootDir = path.resolve(__dirname, '..');
const pagesDir = path.resolve(rootDir, 'pages');
const outFile = path.resolve(rootDir, 'src', 'components', 'pages.ts');

function toPosixPath(p) {
    return p.replaceAll('\\', '/');
}

function ensureTrailingSlash(p) {
    return p.endsWith('/') ? p : `${p}/`;
}

function listPageFolders() {
    if (!fs.existsSync(pagesDir)) {
        throw new Error(
            `Expected a "pages" folder at ${toPosixPath(path.relative(rootDir, pagesDir))}`,
        );
    }

    const dirents = fs.readdirSync(pagesDir, { withFileTypes: true });
    const folders = dirents.filter((d) => d.isDirectory()).map((d) => d.name);

    const missingIndex = [];
    const pages = [];

    for (const folder of folders) {
        const folderAbs = path.resolve(pagesDir, folder);
        const indexAbs = path.resolve(folderAbs, 'index.html');
        if (!fs.existsSync(indexAbs)) {
            missingIndex.push(toPosixPath(path.relative(rootDir, indexAbs)));
            continue;
        }

        pages.push({
            folder,
            path: toPosixPath(path.relative(rootDir, folderAbs)),
        });
    }

    if (missingIndex.length) {
        const message = [
            `Some subfolders in "pages/" are missing an index.html:`,
            ...missingIndex.map((p) => `- ${p}`),
        ].join('\n');
        throw new Error(message);
    }

    pages.sort((a, b) => a.folder.localeCompare(b.folder));
    return pages;
}

function renderPagesTs(pages) {
    const lines = [];

    lines.push('// This file is auto-generated by `pnpm gen:pages`.');
    lines.push('// Do not edit by hand.');
    lines.push('');
    lines.push('export type PageEntry = {');
    lines.push('  folder: string');
    lines.push('  path: string');
    lines.push('}');
    lines.push('');
    lines.push('export const pages: PageEntry[] = [');
    for (const page of pages) {
        lines.push(
            `  { folder: ${JSON.stringify(page.folder)}, path: ${JSON.stringify(
                page.path,
            )} },`,
        );
    }
    lines.push(']');
    lines.push('');

    return lines.join('\n');
}

try {
    const pages = listPageFolders();
    const content = renderPagesTs(pages);

    fs.mkdirSync(path.dirname(outFile), { recursive: true });

    let prev = null;
    try {
        prev = fs.readFileSync(outFile, 'utf8');
    } catch {
        // ignore
    }

    if (prev === content) {
        console.log(
            `${toPosixPath(path.relative(rootDir, outFile))} is up to date (${pages.length} pages).`,
        );
        process.exit(0);
    }

    fs.writeFileSync(outFile, content, 'utf8');
    console.log(
        `Wrote ${toPosixPath(path.relative(rootDir, outFile))} (${pages.length} pages).`,
    );

    const urls = pages.map((p) => `/${ensureTrailingSlash(p.path)}`);
    console.log(`URLs:\n${urls.map((u) => `- ${u}`).join('\n')}`);
} catch (err) {
    console.error(err instanceof Error ? err.message : String(err));
    process.exitCode = 1;
}
